version: "3"

volumes:
  postgis16_data:
  kafka_data:
  zookeeper_data:

services:
  db:
    image: postgis/postgis:16-3.4-alpine
    ports:
      - 5496:5432
    volumes:
      - postgis16_data:/var/lib/postgresql/data/
    env_file:
      - docker.env
    networks:
      - postgres

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    volumes:
      - zookeeper_data:/var/lib/zookeeper
    networks:
      - kafka-net

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKAJS_NO_PARTITIONER_WARNING: 1
    ports:
      - 9092:9092
    volumes:
      - kafka_data:/var/lib/kafka
    networks:
      - kafka-net

networks:
  postgres:
    driver: bridge
  kafka-net:
    driver: bridge
